#! /bin/bash
# QUERY_STRING "id=(003,006)" --> PATTERN "patient:p(003|006)"
export PATTERN=`echo "$QUERY_STRING" | sed 's/,/|/g' | sed 's/id=/patient:p/'`
echo "# Immunology patient data for PATTERN: $PATTERN"
egrep "@prefix|($PATTERN)" $1
exit 0

