#!/usr/bin/perl -w 
# Read TSV patients data and write to stdout as RDF Turtle
print "\@prefix patient: <http://example/patient#> . \n";
print "\@prefix : <http://example/med#> . \n";
while (<STDIN>) 
  {
  if (m/(patient)\t(id)=(\d+)\t(\w+)=(\w+)\t(\w+)=(.*)/)
    { print "patient:p$3 :$4 \"$5\" ; :$6 \"$7\" .\n"; }
  }

