#! /usr/bin/perl -w

# This script will be invoked by run-test.perl as:
#
#	cd '$TESTDIR'
# 	test-script '$RDF_PIPELINE_WWW_DIR'
#
# where $TESTDIR is the full path of the nnnn numbered test directory
# that is being tested, and $RDF_PIPELINE_WWW_DIR is the full path
# of the RDF Pipeline's Apache DOCUMENT_ROOT.
#
# You may customize any part of this script as needed for this test,
# though the most commonly customized part is marked "CUSTOMIZE HERE".  
# The script must exit(0) iff the test passes.

use strict;

my $wwwDir = shift @ARGV || $ENV{RDF_PIPELINE_WWW_DIR} || die;
# Ensure this env var is set, so that pipeline-request.perl can find it:
$ENV{RDF_PIPELINE_WWW_DIR} = $wwwDir;	

############ CUSTOMIZE HERE ################
# Change max to 9:
!system("cp 'setup-files/node/max9' '$wwwDir/node/max'") or die;
!system("cp 'setup-files/node/max9' 'setup-files/node/max'") or die;

# Wait at least 1 second to ensure that Apache will issue a strong ETag
# instead of a weak ETag, as described at:
# https://issues.apache.org/bugzilla/show_bug.cgi?id=42987
sleep(1);

# Invoke the URL, concatenating its output to $wwwDir/test/testout :
my $testUrl = 'http://localhost/node/addone';
!system("../../helpers/pipeline-request.perl GET '$testUrl'") or die;
############################################

exit 0;

