#!/usr/bin/env perl

# BigData SPARQL UPDATE operation.
#
# Copyright 2014 by David Booth
# Code home: http://code.google.com/p/rdf-pipeline/
# See license information at http://code.google.com/p/rdf-pipeline/ 
#
# Usage: $0 [ filename.ru ]

#### TODO: Make it return 1 if there was an error.

################### Generic preparation ####################
use warnings;
my $help = 0;
my $debug = 0;
my $server = "";
use Getopt::Long; # Perl
GetOptions(
                "debug|d" => \$debug,
                "help|h" => \$help,
                "server|s=s" => \$server,
                ) or die "$0: Error reading options.
";
die "Usage: $0 [ filename.ru ]\n" if $help;

$ENV{SPARQL_SERVER} = $server if $server;
$ENV{SPARQL_SERVER} or die "$0: ERROR: SPARQL_SERVER env var is not set.  Examples:
  export SPARQL_SERVER=http://localhost:8080/bigdata/
  export SPARQL_SERVER=http://localhost:8080/openrdf-workbench/repositories/rdf-pipeline-test\n";
@ARGV == 1 || @ARGV == 0 || die "Usage: $0 [ filename.ru ]\n";
my $f = $ARGV[0];
my $tmpDir = $ENV{TMPDIR} || "/tmp";
my $tmp = "";
if (!defined($f)) {
        my $s = join("", <>);
        $tmp = "$tmpDir/sparql-update-$$.ru";
        $f = $tmp;
	open(my $fh, ">$f") || die "$0: ERROR: Cannot create tmp file: $f\n";
	print $fh $s;
	close($fh) || die;
        }
-e $f or die "$0: ERROR: File not found: $f\n";
-f $f or die "$0: ERROR: Not a plain file: $f\n";
my $qf = quotemeta($f);

################### Server-type-specific code ####################
my $dir = $0;
$dir =~ s/\/[^\/]+$//;
my $qdir = quotemeta($dir);
$ENV{SPARQL_SERVER} =~ s|\/$||;  # Strip trailing slash if any
$ENV{SPARQL_SERVER} =~ m/\bbigdata$/ or warn "[WARNING] \$SPARQL_SERVER does not end with \"bigdata\": $ENV{SPARQL_SERVER}\n" if $debug;
my $qss = quotemeta($ENV{SPARQL_SERVER});
# curl -s --data-urlencode  'update@/dev/null' 'http://localhost:8080/openrdf-workbench/repositories/rdf-pipeline-test/update' 
my $cmd = "/usr/bin/curl -s  --data-urlencode  update\@$qf $qss/sparql" ;
warn "cmd: $cmd\n" if $debug;
# !system($cmd) or die "$0: $?\n";
my ($stdout, $stderr) = &BacktickPlus($cmd);
die "$0: $?\n[[\n$stderr\n]]\n" if $?;
warn "$stderr\n" if $stderr =~ m/\S/;
my $expectedResponse = quotemeta("COMMIT: totalElapsed");
$stdout =~ m/COMMIT: totalElapsed/ or die "$0: [ERROR] Unexpected response from $ENV{SPARQL_SERVER}:\n[[\n$stdout\n]]\n";

##################### Cleanup #####################
unlink($tmp) if $tmp;
exit 0;

############## BacktickPlus ##############
# Runs a command like perl `$command`, but returns both stdout and stderr 
# as scalar strings: 
#   my ($stdout, $stderr) = &BacktickPlus($command);
# The exit status is also available in $? .
sub BacktickPlus
{
my $command = shift || die "$0: [ERROR] BacktickPlus called without an argument! ";
my $tmp = "/tmp/BacktickPlus-stderr-$$.txt"; 
my $stdout = `( $command ) 2> $tmp`;
open(my $fh, "<$tmp") || die;
my $stderr = join("", <$fh>);
close($fh) || die;
unlink $tmp || die "$0: [ERROR] BacktickPlus could not remove tmp file: $tmp\n";
return($stdout, $stderr);
}

