#! /usr/bin/perl -w

# Flush the pipeline caches on the current machine.

my $wwwDir = $ENV{'RDF_PIPELINE_WWW_DIR'} or &EnvNotSet('RDF_PIPELINE_WWW_DIR');

foreach my $subdir (qw(cache lm)) {
	my $f = "$wwwDir/$subdir";
	if (-e "$f") {
		my $qf = quotemeta($f);
		my $cmd = "rm -r $qf";
		# warn "$cmd\n";
		!system($cmd) || die; 
		}
	die "$0: Failed to delete $f\n" if -e $f;
	mkdir $f || die "$0: [ERROR] Failed to re-create empty $f\n";
	}
exit 0;


########## EnvNotSet #########
sub EnvNotSet
{
@_ == 1 or die;
my ($var) = @_;
die "ERROR: Environment variable '$var' not set!  Please set it
by editing set_env.sh and then (in bourne shell) issuing the
command '. set_env.sh'\n";
}

