#! /usr/bin/perl -w

# Flush the pipeline caches on the current machine.

my $wwwDir = $ENV{'RDF_PIPELINE_WWW_DIR'} or &EnvNotSet('RDF_PIPELINE_WWW_DIR');
my $qwww = quotemeta($wwwDir);

foreach my $subdir (qw(cache lm)) {
	my $f = "$qwww/$subdir";
	my $cmd = "rm -r $f";
	# warn "$cmd\n";
	`$cmd` if -e "$f";
	die "$0: Failed to delete $f\n" if -e $f;
	mkdir $f || die "$0: [ERROR] Failed to re-create empty $f\n";
	}
exit 0;


########## EnvNotSet #########
sub EnvNotSet
{
@_ == 1 or die;
my ($var) = @_;
die "ERROR: Environment variable '$var' not set!  Please set it
by editing set_env.sh and then (in bourne shell) issuing the
command '. set_env.sh'\n";
}

